-- -- local bufnr, command = 15, { "mvn", "jetty:run", "-f", "games/pom.xml" }
-- --
-- Auto_Run_Job_ID = -1;
--
-- local attach_to_buffer = function(output_bufnr, pattern, command)
--     vim.api.nvim_create_autocmd("BufWritePost", {
--         group = vim.api.nvim_create_augroup("my_autosave", { clear = true }),
--         pattern = pattern,
--         callback = function()
--             local append_data = function(_, data)
--                 if data then
--                     vim.api.nvim_buf_set_lines(output_bufnr, -1, -1, false, data)
--                 end
--             end
--
--             vim.fn.jobstop(Auto_Run_Job_ID)
--
--             Auto_Run_Job_ID = vim.fn.jobstart(command, {
--                 stdout_buffered = true,
--                 on_stdout = append_data,
--                 on_stderr = append_data
--             })
--         end
--     })
-- end
--
-- attach_to_buffer(9, "*java", { "mvn", "jetty:run", "-f", "games/pom.xml" })
--
-- vim.api.nvim_create_user_command("AutoRun", function ()
--     local bufnr = tonumber(vim.api.nvim_get_current_buf())
--     local pattern = vim.fn.input "Pattern: "
--     local command = vim.split(vim.fn.input "Command: ", " ")
--
--     attach_to_buffer(bufnr, pattern, command)
-- end, {})
