import = ["/home/irakli/.config/alacritty/tokyo/tokyo.toml"]

[font]
size = 10

[font.normal]
# family = "Fira Code"
# family = "Liga SFMono Nerd Font"
# family = "MapleMono"
family = "Source Code Pro"

[window]
opacity = 1.0
